<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" file="test_process_rotate.py" name="test_process_rotate.TestProcessRotate-20220623172858" skipped="0" tests="1" time="0.001" timestamp="2022-06-23T17:28:58">
	<testcase classname="test_process_rotate.TestProcessRotate" file="spec/construct/test_process_rotate.py" line="8" name="test_process_rotate" time="0.001" timestamp="2022-06-23T17:28:58">
		<failure message="'\t\xac\x8d\x8d\xed' != 'Hello'" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/travis/build/kaitai-io/ci_targets/tests/spec/construct/test_process_rotate.py", line 10, in test_process_rotate
    self.assertEqual(r.buf1, b"\x48\x65\x6C\x6C\x6F")
AssertionError: '\t\xac\x8d\x8d\xed' != 'Hello'
]]>		</failure>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
