<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" file="test_process_xor_value.py" name="test_process_xor_value.TestProcessXorValue-20220318130449" skipped="0" tests="1" time="0.001" timestamp="2022-03-18T13:04:49">
	<testcase classname="test_process_xor_value.TestProcessXorValue" file="spec/construct/test_process_xor_value.py" line="8" name="test_process_xor_value" time="0.001" timestamp="2022-03-18T13:04:49">
		<failure message="'\x99\x90\x90\xdf\x9d\x9e\x8d' != 'foo bar'" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/travis/build/kaitai-io/ci_targets/tests/spec/construct/test_process_xor_value.py", line 11, in test_process_xor_value
    self.assertEqual(r.buf, b"\x66\x6F\x6F\x20\x62\x61\x72")
AssertionError: '\x99\x90\x90\xdf\x9d\x9e\x8d' != 'foo bar'
]]>		</failure>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
