<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" file="test_valid_fail_max_int.py" name="test_valid_fail_max_int.TestValidFailMaxInt-20200605215723" skipped="0" tests="1" time="0.000" timestamp="2020-06-05T21:57:23">
	<testcase classname="test_valid_fail_max_int.TestValidFailMaxInt" file="spec/python/test_valid_fail_max_int.py" line="9" name="test_valid_fail_max_int" time="0.000" timestamp="2020-06-05T21:57:23">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
