<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_eof_exception_u4.TestEofExceptionU4-20200521225016" tests="1" file="test_eof_exception_u4.py" time="0.000" timestamp="2020-05-21T22:50:16" failures="0" errors="0" skipped="0">
	<testcase classname="test_eof_exception_u4.TestEofExceptionU4" name="test_eof_exception_u4" time="0.000" timestamp="2020-05-21T22:50:16" file="spec/python/test_eof_exception_u4.py" line="9">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
</testsuite>
